#!/usr/bin/env bash
set -euo pipefail

# https://tdlib.github.io/td/build.html
# Function to install packages based on the operating system
install_packages() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    if ! xcode-select -p &>/dev/null; then
      xcode-select --install
      # Run xcodebuild -runFirstLaunch to complete setup
      sudo xcodebuild -runFirstLaunch
    fi

    brew list gperf &>/dev/null || brew install gperf
    brew list cmake &>/dev/null || brew install cmake
    brew list openssl@3 &>/dev/null || brew install openssl@3
    brew list ninja &>/dev/null || brew install ninja

  elif [[ -n "$(command -v pacman)" ]]; then
    # Arch Linux
    local packages=(gperf cmake openssl ninja)
    local missing=()
    local package
    for package in "${packages[@]}"; do
      pacman -Q "$package" &>/dev/null || missing+=("$package")
    done
    if ((${#missing[@]})); then
      sudo pacman -S --needed "${missing[@]}"
    fi
  else
    echo "Unsupported OS or missing package manager."
    exit 1
  fi
}

# Set the target directory for cloning the repository
TARGET_DIR="${TDLIB_SOURCE_DIR:-$HOME/td}"
BUILD_DIR="$TARGET_DIR/build"
LOCAL_INSTALL_DIR="$TARGET_DIR/tdlib"
if command -v nproc &>/dev/null; then
  DEFAULT_BUILD_JOBS=$(nproc)
else
  DEFAULT_BUILD_JOBS=$(sysctl -n hw.logicalcpu)
fi
BUILD_JOBS="${TDLIB_BUILD_JOBS:-$DEFAULT_BUILD_JOBS}"
REQUESTED_COMMIT="${1:-}"

# Clone or update the tdlib repository
if [ ! -d "$TARGET_DIR" ]; then
  git clone https://github.com/tdlib/td.git "$TARGET_DIR"
else
  git -C "$TARGET_DIR" fetch
fi

BUILT_COMMIT_FILE="$TARGET_DIR/.built_commit"
SYSTEM_BUILT_COMMIT_FILE="$TARGET_DIR/.built_commit_usr_local"

# If a commit hash is provided as an argument, checkout that commit
if [ -n "$REQUESTED_COMMIT" ]; then
  git -C "$TARGET_DIR" checkout "$REQUESTED_COMMIT"
else
  git -C "$TARGET_DIR" checkout master
  git -C "$TARGET_DIR" pull --ff-only
fi

LOCAL=$(git -C "$TARGET_DIR" rev-parse HEAD)
BUILT=$(cat "$BUILT_COMMIT_FILE" 2>/dev/null || true)
SYSTEM_BUILT=$(cat "$SYSTEM_BUILT_COMMIT_FILE" 2>/dev/null || true)

if [[ "$OSTYPE" == "darwin"* ]]; then
  UP_TO_DATE=true
else
  UP_TO_DATE=$([ "$LOCAL" = "$SYSTEM_BUILT" ] && echo true || echo false)
fi

if [ "$LOCAL" = "$BUILT" ] && [ "$UP_TO_DATE" = true ]; then
  echo "Source and installed TDLib are up to date; continuing with an incremental rebuild."
fi

install_packages

# Explicitly requested full rebuild: discard only TDLib's generated build tree.
if [ "${TDLIB_FORCE_REBUILD:-0}" = 1 ] && [ -d "$BUILD_DIR" ]; then
  echo "TDLIB_FORCE_REBUILD=1: removing the existing build directory..."
  rm -rf -- "$BUILD_DIR"
fi

# Ninja cannot reuse a build tree generated by Unix Makefiles.  Remove the
# directory once when migrating; subsequent builds keep it for incremental use.
if [ -f "$BUILD_DIR/CMakeCache.txt" ] &&
  ! grep -q '^CMAKE_GENERATOR:INTERNAL=Ninja$' "$BUILD_DIR/CMakeCache.txt"; then
  echo "Migrating the TDLib build directory to Ninja..."
  rm -rf -- "$BUILD_DIR"
fi

# Configure with Ninja.  Install into the user-owned staging directory while
# building, then copy the same artifacts to /usr/local for telega.
if [[ "$OSTYPE" == "darwin"* ]]; then
  OPENSSL_ROOT_DIR="${TDLIB_OPENSSL_ROOT_DIR:-$(brew --prefix openssl@3)}"
  cmake \
    -S "$TARGET_DIR" \
    -B "$BUILD_DIR" \
    -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DOPENSSL_ROOT_DIR="$OPENSSL_ROOT_DIR" \
    -DCMAKE_INSTALL_PREFIX:PATH="$LOCAL_INSTALL_DIR"
else
  cmake \
    -S "$TARGET_DIR" \
    -B "$BUILD_DIR" \
    -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX:PATH="$LOCAL_INSTALL_DIR"
fi

cmake --build "$BUILD_DIR" --target install --parallel "$BUILD_JOBS"

# Keep /usr/local in sync for consumers like telega that link against it.
sudo cmake --install "$BUILD_DIR" --prefix /usr/local
git -C "$TARGET_DIR" rev-parse HEAD >"$BUILT_COMMIT_FILE"
git -C "$TARGET_DIR" rev-parse HEAD >"$SYSTEM_BUILT_COMMIT_FILE"
