;;; lib-format.el --- Insert description here -*- lexical-binding: t -*-
;;; Commentary:
;;; Code:

(defun +mybatis-edit-sql-block ()
  "Edit MyBatis SQL block in a separate buffer with sql-mode."
  (interactive)
  (save-excursion
    (when (re-search-backward "<\\(select\\|insert\\|update\\|delete\\)[^>]*>" nil t)
      (let* ((tag-type (match-string 1))
             (tag-start (match-end 0))
             (original-buffer (current-buffer))
             (original-window (selected-window))
             (window-config (current-window-configuration)))
        (when (re-search-forward (format "</%s>" tag-type) nil t)
          (let* ((tag-end (match-beginning 0))
                 (sql-content (buffer-substring-no-properties tag-start tag-end))
                 (edit-buffer (generate-new-buffer (format "*MyBatis SQL: %s*" tag-type)))
                 (base-indent nil)
                 (tag-placeholder-map '())
                 (param-placeholder-map '())
                 (comment-placeholder-map '()))
            (goto-char tag-start)
            (beginning-of-line)
            (when (looking-at "^\\([ \t]*\\)")
              (setq base-indent (+ (length (match-string 1)) 4)))
            (with-current-buffer edit-buffer
              (insert sql-content)
              ;; Replace XML comments
              (goto-char (point-min))
              (let ((counter 0))
                (while (re-search-forward "<!--\\(.*?\\)-->" nil t)
                  (let ((original (match-string 0))
                        (placeholder (format "/* __COMMENT_%d__ */" counter)))
                    (push (cons placeholder original) comment-placeholder-map)
                    (replace-match placeholder t t)
                    (setq counter (1+ counter)))))
              ;; Replace MyBatis parameters
              (goto-char (point-min))
              (let ((counter 0))
                (while (re-search-forward "\\(#\\|\\$\\){[^}]+}" nil t)
                  (let ((original (match-string 0))
                        (placeholder (format "? /* __PARAM_%d__ */" counter)))
                    (push (cons placeholder original) param-placeholder-map)
                    (replace-match placeholder t t)
                    (setq counter (1+ counter)))))
              ;; Replace MyBatis dynamic tags - opening tags
              (goto-char (point-min))
              (let ((counter 0))
                (while (re-search-forward "<\\(if\\|foreach\\|set\\|trim\\|choose\\|when\\|otherwise\\|where\\)\\(\\s-+[^>]*\\)?>" nil t)
                  (let* ((full-tag (match-string 0))
                         (tag-name (match-string 1))
                         (placeholder (if (string= tag-name "where")
                                          (format "/* __WHERE_OPEN_%d__ */\nWHERE" counter)
                                        (format "/* __TAG_OPEN_%d__ */" counter))))
                    (push (cons (if (string= tag-name "where")
                                    (format "/* __WHERE_OPEN_%d__ */" counter)
                                  placeholder) full-tag) tag-placeholder-map)
                    (replace-match placeholder t t)
                    (setq counter (1+ counter)))))
              ;; Replace MyBatis dynamic tags - closing tags
              (goto-char (point-min))
              (let ((counter 0))
                (while (re-search-forward "</\\(if\\|foreach\\|set\\|trim\\|choose\\|when\\|otherwise\\|where\\)>" nil t)
                  (let* ((full-tag (match-string 0))
                         (tag-name (match-string 1))
                         (placeholder (if (string= tag-name "where")
                                          (format "/* __WHERE_CLOSE_%d__ */" counter)
                                        (format "/* __TAG_CLOSE_%d__ */" counter))))
                    (push (cons placeholder full-tag) tag-placeholder-map)
                    (replace-match placeholder t t)
                    (setq counter (1+ counter)))))
              ;; Replace XML entities
              (goto-char (point-min))
              (while (re-search-forward "&lt;" nil t) (replace-match "<" t t))
              (goto-char (point-min))
              (while (re-search-forward "&gt;" nil t) (replace-match ">" t t))
              (goto-char (point-min))
              (while (re-search-forward "&amp;" nil t) (replace-match "&" t t))
              (goto-char (point-min))
              (while (re-search-forward "&quot;" nil t) (replace-match "\"" t t))
              (goto-char (point-min))
              (while (re-search-forward "&apos;" nil t) (replace-match "'" t t))
              (goto-char (point-min))
              (while (re-search-forward "\n\n\n+" nil t) (replace-match "\n\n"))
              (sql-mode)
              (setq-local +mybatis-original-buffer original-buffer)
              (setq-local +mybatis-original-window original-window)
              (setq-local +mybatis-window-config window-config)
              (setq-local +mybatis-tag-start tag-start)
              (setq-local +mybatis-tag-end tag-end)
              (setq-local +mybatis-base-indent base-indent)
              (setq-local +mybatis-tag-placeholder-map tag-placeholder-map)
              (setq-local +mybatis-param-placeholder-map param-placeholder-map)
              (setq-local +mybatis-comment-placeholder-map comment-placeholder-map)
              (use-local-map (copy-keymap sql-mode-map))
              (local-set-key (kbd "C-c C-c") #'+mybatis-commit-sql-block)
              (local-set-key (kbd "C-c C-k") #'+mybatis-abort-sql-block)
              (goto-char (point-min))
              (message "Edit SQL (%s), then C-c C-c to commit or C-c C-k to abort" sql-product))
            (pop-to-buffer edit-buffer)))))))

(defun +mybatis-commit-sql-block ()
  "Commit the edited SQL back to the original MyBatis XML."
  (interactive)
  (let ((edited-sql (buffer-substring-no-properties (point-min) (point-max)))
        (original-buffer +mybatis-original-buffer)
        (window-config +mybatis-window-config)
        (tag-start +mybatis-tag-start)
        (tag-end +mybatis-tag-end)
        (base-indent +mybatis-base-indent)
        (tag-placeholder-map +mybatis-tag-placeholder-map)
        (param-placeholder-map +mybatis-param-placeholder-map)
        (comment-placeholder-map +mybatis-comment-placeholder-map))
    (with-temp-buffer
      (insert edited-sql)
      ;; Convert comparison operators back to XML entities
      (goto-char (point-min))
      (while (re-search-forward " <= " nil t) (replace-match " &lt;= " t t))
      (goto-char (point-min))
      (while (re-search-forward " >= " nil t) (replace-match " &gt;= " t t))
      (goto-char (point-min))
      (while (re-search-forward " < " nil t) (replace-match " &lt; " t t))
      (goto-char (point-min))
      (while (re-search-forward " > " nil t) (replace-match " &gt; " t t))
      ;; Restore placeholders: comments first
      (dolist (pair comment-placeholder-map)
        (goto-char (point-min))
        (while (search-forward (car pair) nil t)
          (replace-match (cdr pair) t t)))
      ;; Restore parameters
      (dolist (pair param-placeholder-map)
        (let ((placeholder (car pair))
              (original (cdr pair)))
          (goto-char (point-min))
          ;; Replace "? /* __PARAM_123__ */" patterns,
          ;; allowing for formatter-added whitespace.
          (while (re-search-forward
                  (concat "\\?\\s-*" (regexp-quote "/* __PARAM_")
                          "[0-9]+\\s-*__\\s-*\\*/")
                  nil t)
            (replace-match original t t))))
      ;; Restore tags
      (dolist (pair tag-placeholder-map)
        (goto-char (point-min))
        (while (search-forward (car pair) nil t)
          (replace-match (cdr pair) t t)))
      ;; Clean up <where> tags - remove WHERE keyword
      (goto-char (point-min))
      (while (re-search-forward "<where>\\s-*\n?\\s-*WHERE\\s-*\n?" nil t)
        (replace-match "<where>\n"))
      ;; Add indentation for MyBatis tags and comments
      (goto-char (point-min))
      (let ((indent-level 0)
            (extra-indent "    "))
        (while (not (eobp))
          (beginning-of-line)
          (when (looking-at "\\s-*</?\\(where\\|if\\|foreach\\|set\\|trim\\|choose\\|when\\|otherwise\\)")
            (when (looking-at "\\s-*</")
              (setq indent-level (max 0 (1- indent-level))))
            (delete-horizontal-space)
            (insert (make-string (* indent-level (length extra-indent)) ?\s))
            (when (looking-at "\\s-*<[^/]")
              (setq indent-level (1+ indent-level))))
          (when (looking-at "\\s-*<!--")
            (delete-horizontal-space)
            (insert (make-string (* indent-level (length extra-indent)) ?\s)))
          (forward-line 1)))
      ;; Add base indentation
      (let ((indent-str (make-string base-indent ?\s)))
        (goto-char (point-min))
        (insert "\n")
        (goto-char (point-min))
        (forward-line 1)
        (while (not (eobp))
          (unless (looking-at "^$") (insert indent-str))
          (forward-line 1)))
      (setq edited-sql (buffer-substring-no-properties (point-min) (point-max))))
    (with-current-buffer original-buffer
      (save-excursion
        (goto-char tag-start)
        (delete-region tag-start tag-end)
        (insert edited-sql)
        (when (looking-at "[ \t]*</\\(select\\|insert\\|update\\|delete\\)>")
          (beginning-of-line)
          (delete-horizontal-space)
          (insert (make-string (- base-indent 4) ?\s)))))
    (kill-buffer)
    (set-window-configuration window-config)
    (message "SQL block updated")))

(defun +mybatis-abort-sql-block ()
  "Abort editing and close the SQL edit buffer."
  (interactive)
  (let ((window-config +mybatis-window-config))
    (kill-buffer)
    (set-window-configuration window-config)
    (message "Edit aborted")))

(provide 'lib-format)
;;; lib-format.el ends here
